title: first blog site
author: GitHub User Akanksha-code
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:
hello all this is my first experience on github for github pages.
i am doing it all by myself and proud of myself.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
